### PR TITLE
Combine relative path urls

### PR DESCRIPTION
**Pull request by elglogins**
The current solution doesn't handle relative paths correctly.

### Example:
Media domain: `https://blob.com/container`
Media relative url in Umbraco: `/media/123.png`

Outcome: `https://blob.com/media/123.png`
Expected outcome: `https://blob.com/container/media/123.png`

### CODE REVIEW

**Comment by storkie** [comment]
Did a bit of fiddling with it:
https://dotnetfiddle.net/CXCihA

**Comment by elglogins** [comment]
> Did a bit of fiddling with it: https://dotnetfiddle.net/CXCihA

Sooo, do you want me to move it into the extension method?

**Comment by storkie** [comment]
> > Did a bit of fiddling with it: https://dotnetfiddle.net/CXCihA
> 
> Sooo, do you want me to move it into the extension method?

That's up to you. Results are the same but as you already have StringExtensions I think it would make sense.

**Review by jthind — CHANGES_REQUESTED** [review]
The `Uri` class already has a constructor for combining base and relative url. Just use `new Uri(baseUrl, relativeUrl)`

**Comment by elglogins** [comment]
> The `Uri` class already has a constructor for combining base and relative url. Just use `new Uri(baseUrl, relativeUrl)`

This particular code you are referring to was the one that clears up relative paths from base url.

**Comment by jthind** [comment]
> 

Doh, I'm an idiot 😑

**Comment by elglogins** [comment]
> 

Adjusted

**Comment by elglogins** [comment]
> > > Did a bit of fiddling with it: https://dotnetfiddle.net/CXCihA
> > 
> > 
> > Sooo, do you want me to move it into the extension method?
> 
> That's up to you. Results are the same but as you already have StringExtensions I think it would make sense.

Adjusted

**Review by jthind — APPROVED** [review]

**Pull request merged**
