### PR TITLE
Feature: Enhanced Metadata Management

### PR DESCRIPTION
**Pull request by aochmann**
Hi all 🤲🏼
I want to introduce specialized property metadata service objects dedicated to selected objects. This change aims to segregate dedicated metadata mapping for selected content/media, providing greater control over extensive metadata manipulation, which is applicable to specific entities

For example:

```csharp
internal class SlugMetaDataService : IEnterspeedPropertyMetaDataService
{
    public bool IsAllowed(IPublishedContent content)
        => content is not null;

    public void MapAdditionalMetaData(Dictionary<string, IEnterspeedProperty> metaData, IPublishedContent content, string culture)
    {
        // some logic

        metaData["slug"] = new ArrayEnterspeedProperty("slug", slug);
    }
}
```

I've retained the previous method to ensure backward compatibility.

If possible, I would greatly appreciate it if you could label this pull request with HACKTOBERFEST-ACCEPTED. Thank you!🙌🏻 

image

Cheers,
Adrian

### CODE REVIEW

**Comment by jesperweber** [comment]
Thank you for the PR @aochmann :-)

We will get back to you as soon as we have looked into it.

**Comment by jesperweber** [comment]
Hi @aochmann I like the concept of separating meta data for different type into separate classes if you are different. Also it works nice in combination with the existing `MapAdditionalProperties` functions. 

I do how error get an exception when I start up the Umbraco project: The type `EnterspeedPropertyMetaDataCollection` can't be registered as a dependency in `EnterspeedPropertyService`

System.AggregateException: 'Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Enterspeed.Source.UmbracoCms.Services.IEnterspeedPropertyService Lifetime: Transient ImplementationType: Enterspeed.Source.UmbracoCms.Services.EnterspeedPropertyService': Unable to resolve service for type 'Enterspeed.Source.UmbracoCms.DataPropertyValueConverters.EnterspeedPropertyMetaDataCollection' while attempting to activate 'Enterspeed.Source.UmbracoCms.Services.EnterspeedPropertyService'.) (Error while validating the service descriptor 'ServiceType: Enterspeed.Source.UmbracoCms.Handlers.Content.EnterspeedContentPublishJobHandler Lifetime: Singleton ImplementationType: Enterspeed.Source.UmbracoCms.Handlers.Content.EnterspeedContentPublishJobHandler': Unable to resolve service for type 'Enterspeed.Source.UmbracoCms.DataPropertyValueConverters.EnterspeedPropertyMetaDataCollection' while attempting to activate 'Enterspeed.Source.UmbracoCms.Services.EnterspeedPropertyService'.) (Error while validating the service descriptor 'ServiceType: Enterspeed.Source.UmbracoCms.Handlers.Dictionaries.EnterspeedDictionaryItemPublishJobHandler Lifetime: Singleton ImplementationType: Enterspeed.Source.UmbracoCms.Handlers.Dictionaries.EnterspeedDictionaryItemPublishJobHandler': Unable to resolve service for type 'Enterspeed.Source.UmbracoCms.DataPropertyValueConverters.EnterspeedPropertyMetaDataCollection' while attempting to activate 'Enterspeed.Source.UmbracoCms.Services.EnterspeedPropertyService'.) (Error while validating the service descriptor 'ServiceType: Enterspeed.Source.UmbracoCms.Handlers.PreviewContent.EnterspeedPreviewContentPublishJobHandler Lifetime: Singleton ImplementationType: Enterspeed.Source.UmbracoCms.Handlers.PreviewContent.EnterspeedPreviewContentPublishJobHandler': Unable to resolve service for type 'Enterspeed.Source.UmbracoCms.DataPropertyValueConverters.EnterspeedPropertyMetaDataCollection' while attempting to activate 'Enterspeed.Source.UmbracoCms.Services.EnterspeedPropertyService'.) (Error while validating the service descriptor 'ServiceType: Enterspeed.Source.UmbracoCms.Handlers.PreviewDictionaries.EnterspeedPreviewDictionaryItemPublishJobHandler Lifetime: Singleton ImplementationType: Enterspeed.Source.UmbracoCms.Handlers.PreviewDictionaries.EnterspeedPreviewDictionaryItemPublishJobHandler': Unable to resolve service for type 'Enterspeed.Source.UmbracoCms.DataPropertyValueConverters.EnterspeedPropertyMetaDataCollection' while attempting to activate 'Enterspeed.Source.UmbracoCms.Services.EnterspeedPropertyService'.) (Error while validating the service descriptor 'ServiceType: Enterspeed.Source.UmbracoCms.Handlers.Media.EnterspeedMediaPublishJobHandler Lifetime: Singleton ImplementationType: Enterspeed.Source.UmbracoCms.Handlers.Media.EnterspeedMediaPublishJobHandler': Unable to resolve service for type 'Enterspeed.Source.UmbracoCms.DataPropertyValueConverters.EnterspeedPropertyMetaDataCollection' while attempting to activate 'Enterspeed.Source.UmbracoCms.Services.EnterspeedPropertyService'.) (Error while validating the service descriptor 'ServiceType: Enterspeed.Source.UmbracoCms.Handlers.PreviewMedia.EnterspeedPreviewMediaPublishJobHandler Lifetime: Singleton ImplementationType: Enterspeed.Source.UmbracoCms.Handlers.PreviewMedia.EnterspeedPreviewMediaPublishJobHandler': Unable to resolve service for type 'Enterspeed.Source.UmbracoCms.DataPropertyValueConverters.EnterspeedPropertyMetaDataCollection' while attempting to activate 'Enterspeed.Source.UmbracoCms.Services.EnterspeedPropertyService'.)'

**Comment by aochmann** [comment]
Hi @jesperweber maybe I forgot about some dependency registration. Let me check that and I will come back to you.

**Comment by aochmann** [comment]
Hi @jesperweber should be now fixed 😉 - I forgot about collection registration.

**Comment by jesperweber** [comment]
Thank you for the PR @aochmann it has been merged and I will do the same for data properties and not only metadata properties :-)

**Pull request merged**
