### PR TITLE
Add support for new media picker

### PR DESCRIPTION
**Pull request by elglogins**
I noticed that v9 package, is missing the property value mapper for the new media picker.

### CODE REVIEW

**Comment by emilras** [comment]
@storkie @jthind Could one of you please have a look? 😁

**Review by jthind — APPROVED** [review]

**Comment by elglogins** [comment]
@emilras @jthind @storkie 

Thing is that, MediaPicker3 on v9 project is not a problem, but for v8, do you have some idea how to include it in build and configuration so its only available when users have umbraco 8.14.0+ ?

https://our.umbraco.com/Documentation/Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Media-Picker-3/index-v8

**Comment by Malthebp** [comment]
@elglogins you might be able to make a compilation constant and then in the composer you can make an if statement, to check that the Umbraco version is higher than 8.14: 
https://stackoverflow.com/a/64434767
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives

I haven't tried, but maybe it is possible. :-)

**Comment by elglogins** [comment]
> @elglogins you might be able to make a compilation constant and then in the composer you can make an if statement, to check that the Umbraco version is higher than 8.14: https://stackoverflow.com/a/64434767 https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives
> 
> I haven't tried, but maybe it is possible. :-)

Cool, I've looked into it briefly, but still lost, since couldn't find some more info or examples.

Anybody has experience with CAKE build?

**Comment by elglogins** [comment]
After some time off of this issue, I looked at it again but still cannot wrap my head around it. Any input is more than welcome :-)

**Comment by emilras** [comment]
> After some time off on this issue, I looked at it again but still cannot wrap my head around it. Any input is more than welcome :-)

Could you outline the outstanding questions/issues?

**Comment by elglogins** [comment]
> > After some time off on this issue, I looked at it again but still cannot wrap my head around it. Any input is more than welcome :-)
> 
> Could you outline the outstanding questions/issues?

Challenge is to make sure that the following functionality - MediaPicker3 value mapper and its configuration on the composer - is available only when the project has resolved NuGet reference to Umbraco 8.14+

**Comment by emilras** [comment]
> > > After some time off on this issue, I looked at it again but still cannot wrap my head around it. Any input is more than welcome :-)
> > 
> > 
> > Could you outline the outstanding questions/issues?
> 
> Challenge is to make sure that the following functionality - MediaPicker3 value mapper and its configuration on the composer - is available only when the project has resolved NuGet reference to Umbraco 8.14+

Hmm, yeah, not really any *good* solution from me on that one. But a list of random ideas: 

Should it be different NuGet packages?
Should the MediaPicker3 be it's own package that can be optional loaded?
Should we just provide the source code, so the developers can them on their own?
Perhaps we can forget about this feature for Umbraco v8 and only have it backed ind for v9?

**Comment by elglogins** [comment]
V8 will be covered in a separate pull request/solution.

**Pull request merged**
