### PR TITLE
#831 : added optional text on placeholders

### PR DESCRIPTION
**Pull request by MHove89**

### CODE REVIEW

**Comment by MHove89** [comment]
It says "Add link to "Sources" as well." In the issue.
 Where do we expect this to link to? The documentation or the admin section? 
 @jesperweber @emilras

**Comment by MHove89** [comment]
Tooltip added to api key label

image

**Review by jesperweber — COMMENTED** [review]
I really like solution for this. 

Now that we have the option we could maybe add it to the other fields as well?

Enterspeed endpoint - The value should be https://api.enterspeed.com

Media domain - Enter a custom domain (can include a path as well) if you want to use another domain than the Umbraco domain for your media files.

Preview API Key - Create a separate source in the Enterspeed app and provide the API key here.

**Comment by MHove89** [comment]
> I really like solution for this.
> 
> Now that we have the option we could maybe add it to the other fields as well?
> 
> Enterspeed endpoint - The value should be https://api.enterspeed.com
> 
> Media domain - Enter a custom domain (can include a path as well) if you want to use another domain than the Umbraco domain for your media files.
> 
> Preview API Key - Create a separate source in the Enterspeed app and provide the API key here.
> 
> What do you think?

I agree. Will get to it :)

**Comment by MHove89** [comment]
@jesperweber Updated :)

**Review by jesperweber — APPROVED** [review]
Looking great

**Pull request merged**
