### PR TITLE
Feature/2812 better dictionary handling

### PR DESCRIPTION
**Pull request by MHove89**
Hi @jesperweber 
Here are some of the changes that we have discussed. 

I have merged the code from Elgars extension to implement a virtual root source-entity for dictionaries.
1 root source-entity per culture will be created.

https://github.com/elglogins/Enterspeed.Contrib.Source.UmbracoCms.V9.RootDictionaryItem

Furthermore some refactoring/cleanup has been done in the jobshandler. I have been trying to explain and simplfiy things a bit more. Feel free to reach out to me regarding this.

### CODE REVIEW

**Comment by jesperweber** [comment]
This is working nicely.

Once again thinking about breaking changes. 

Today dictionary items at the root level don't have a `originParentId` and customers can have used this in a condition to do a recursive loop through all dictionary items. If we introduce a new originParentId then it could impact existing schemas.

Maybe we need to add a configuration, like `enableDictionaryRootItem`, where need to enable it? Do you have any insight in this @emilras?

**Comment by emilras** [comment]
@jesperweber No, sorry, I don't recall seeing either it being used in the way you describe or not...

But we can bump the version and declare it a "potential" breaking chance?

**Comment by elglogins** [comment]
> 

Briefly looking at common dictionary schemas, this shouldn't be an issue. In normal (todays) dictionary schema, there is $lookup to fetch all where `type is umbDictionary`, sometimes with a little tweak of extra condition like `properties.culture` or so.

**Comment by jesperweber** [comment]
> This is working nicely.
> 
> Once again thinking about breaking changes.
> 
> Today dictionary items at the root level don't have a `originParentId` and customers can have used this in a condition to do a recursive loop through all dictionary items. If we introduce a new originParentId then it could impact existing schemas.
> 
> Maybe we need to add a configuration, like `enableDictionaryRootItem`, where users need to enable it? Do you have any insight in this @emilras?

**Comment by jesperweber** [comment]
> > 
> 
> Very very valid point guys! I know for a fact that some tenants used to have old schema versions that would have similar $lookup query: `type eq 'umbDictionary' and originParentId eq null`, recently I don't think anyone has been using it, since users realized that `originParentId` was useless. But,.. what prevents them of deploying an older version? 🤔 😶‍🌫️
> 
> I think @emilras idea with bumping version and marking as potential breaking change is most optimal solution that we have.

Agree, lets bump the version because of the potential breaking change. Then we make have the new dictionaryRootItem enabled be default for new installations. I still think it would be nice with a configuration in  and we can have a configuration in appsettings.json where existing installation could disable it if it's a breaking change for them.

**Comment by emilras** [comment]
Yes, a setting is great. I would just hate to not see adaptation because of something that potential could be an issue for 1 or 2 customers. Let's get it done :)

**Comment by MHove89** [comment]
Optional setting to disable root dictionaries has now been added @jesperweber @emilras

**Review by jesperweber — APPROVED** [review]
Looking good.

**Pull request merged**
