### PR TITLE
Added missing area during umbraco 7 package installation

### PR DESCRIPTION
**Pull request by jesperweber**

### CODE REVIEW

**Review by MHove89 — APPROVED** [review]
LGTM 👍 Do you want me to test it, or do you feel confident it works? Seems pretty straight forward.

**Comment by jesperweber** [comment]
> LGTM 👍 Do you want me to test it, or do you feel confident it works? Seems pretty straight forward.

You are more than welcome to test it out. I have also test it, but people always do thing different so you might find something I didn't find :-)

**Comment by MHove89** [comment]
If i remove the <area>content</area> from the areas element, it does not get populates. Only if i remove the whole <areas> element. 

Is this expected?

**Review by MHove89 — DISMISSED** [review]
Works after latest changes ! :)

**Pull request merged**
