### PR TITLE
Added Umbraco 15 support

### PR DESCRIPTION
**Pull request by MHove89**
We need to release a new vesion of Source.Sdk, which should then be referenced. I have temporarily referenced the alpha verison i prepared.

### CODE REVIEW

**Comment by jesperweber** [comment]
Support block variations and blocks as nodes (source entities).

**Comment by MHove89** [comment]
> Support block variations and blocks as nodes (source entities).

This has been tested and works

Content property on the page is not shared. Blocks inside the property can vary by culture. This is done to achieve the same content structure across languages, and to ensure that indivudal content in the blocks varys by culture.

image
image
image
image
image
image

**Comment by jesperweber** [comment]
The block variation seems to work yes. But I still get an error trying to ingest an element type from the content tree.

image

image

**Review by jesperweber — APPROVED** [review]

**Comment by MHove89** [comment]
Updated reference for new SDK

**Review by jesperweber — APPROVED** [review]

**Pull request merged**
