### PR TITLE
feat: added culture provider for centralised culture calculation

### PR DESCRIPTION
**Pull request by K3llr**
@jesperweber An approach to handling cultures for nodes without vary-by-culture where the culture of the domain is used if present otherwise fallback to default language

### CODE REVIEW

**Comment by jesperweber** [comment]
Hi @K3llr, thanks so much for the PR :-)

A node that does not vary-by-culture does only exist in one version in Umbraco and should also only exist in one version in Enterspeed, this is also the case with the new PR, so all good here. But we if we have two domains we are ingesting the node two times just with the same id (that's why we still only have one entity in Enterspeed) because `UmbracoEntityIdentityService` still uses DefaultCulture.

So if not using the domain from the default culture, what domain should we then use? 

- The default culture might not have a domain, so we ingest no domain (This was the original logic)
- What if multiple domains is added with same or different cultures (With this PR we take the last domain)

As we currently only support one url pr source entity in Enterspeed it might be okay to just take the first or last domain.

I really like the `UmbracoCultureProvider` which also makes it possible to override. But we are still using DefaultCulture in other places, like `UmbracoEntityIdentityService`. This means that we might read the domain for the da-DK culture but the culture and the id in Enterspeed will use defaultCulture which might be en-US, I don't think this is logical.

It think it would makes sense to use `UmbracoCultureProvider` everywhere we need the culture for a node, so if we use the domain from da-DK culture we also use the same culture on the node. 
Also I think if a nodes does not vary-by-culture `UmbracoCultureProvider` should only return one culture, maybe just the culture for the first domain as we only support one culture and domain pr entity in Enterspeed.

What do you guys think about this?

**Comment by K3llr** [comment]
@jesperweber I agree with you.

> But if we have two domains we are ingesting the node two times just with the same id (that's why we still only have one entity in Enterspeed) because UmbracoEntityIdentityService still uses DefaultCulture.

Makes perfect sense. I guess this is due to me not being fully familiar with the internal workings of Enterspeed. I thought I might get multiple versions in Enterspeed in the case of multiple domains. Did not test though. 

> As we currently only support one url pr source entity in Enterspeed it might be okay to just take the first or last domain.

My first implementation was to use the first domain if any. Happy with this approach.

> I really like the UmbracoCultureProvider which also makes it possible to override. But we are still using DefaultCulture in other places, like UmbracoEntityIdentityService. 

Happy to hear. If you don't like the implementation that includes the domain culture and you want to stick with the original functionality, you can easily change the provider to support the original functionality - and, I could easily overwrite it with the current functionality. Actually, my first thought was to just implement the existing functionality and then override it my self later.

> This means that we might read the domain for the da-DK culture but the culture and the id in Enterspeed will use defaultCulture which might be en-US, I don't think this is logical.

Agree. I found it odd that the origin id in my case was 76765-en while the culture was da. Would be great if the origin id was 76765-da instead.

> It think it would makes sense to use UmbracoCultureProvider everywhere we need the culture for a node, so if we use the domain from da-DK culture we also use the same culture on the node.

Agree. This comes down to my lack of knowledge about the source. If I had known I would have implemented everywhere.

> Also I think if a nodes does not vary-by-culture UmbracoCultureProvider should only return one culture, maybe just the culture for the first domain as we only support one culture and domain pr entity in Enterspeed.

Agree

**Comment by jesperweber** [comment]
I have updated the branch https://github.com/enterspeedhq/enterspeed-source-umbraco-cms/tree/feature/culture-provider with the changes we talked about with a minor change.

The `UmbracoCultureProvider` is changed from having a method for `GetCultures` to have methods one for `GetCulturesForCultureVariant` and one for `GetCultureForNonCultureVariant`. The reason behind this is that we don't want to allow developers when customizing the `UmbracoCultureProvider` to be able to return multiple culture for nodes that does not vary by culture.

You can still do the changes you need as you can just change the logic for the `GetCultureForNonCultureVariant` method.

We still have the same default business logic as before, where nodes the does not vary by culture uses the Default culture, to avoid creating a breaking change.

Two things to bare in mind. 

1. The culture and the id of a node that does not vary by culture will match the culture of the domain. This means that if you change the logic to, lets says using a danish culture and domain, you will ingest new nodes as the id of the nodes will change.
2. If you change the logic of the `GetCultureForNonCultureVariant` method to some "fussy" logic that just returns the last culture and domain. Added a new culture and hostnames will suddently create new nodes and use a new culture. But this is of course up to the developer to handle the custom logic in the method they override.

Will you guys have a look at it and see if you agree and if it's working for you as well.

**Comment by K3llr** [comment]
@jesperweber Good point about separating the method for getting cultures into one for culture and non-culture variance. I reviewed the code, and I am happy with the changes. Could you release an alpha with the changes while we wait for a proper release?

**Comment by jesperweber** [comment]
@K3llr A new alpha2 release has been published, it should be ready on nuget in a couple of minutes.

**Pull request merged**
